services:
  adguard-home:
    container_name: adguard-home
    image: adguard/adguardhome:v0.107.71
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "3000:3000/tcp"
    volumes:
      - ./data/work:/opt/adguardhome/work/data
      - ./data/conf:/opt/adguardhome/conf

