services:
    adguard-home:
        container_name: adguard-home
        image: adguard/adguardhome:v0.107.72
        restart: unless-stopped
        ports:
            - "53:53/tcp"
            - "53:53/udp"
        environment:
            ADGUARD_HOME_DEFAULT_WEB_PORT: 3000
        volumes:
            - ./data/work:/opt/adguardhome/work/data
            - ./data/conf:/opt/adguardhome/conf
        networks:
            - proxy-internal

networks:
    proxy-internal:
        external: true
